### ISSUE TITLE
FuzzySet operators error

### ISSUE THREAD

**Issue by RaphaelS1** [xoopR/set6#41]
There is ambiguity in these so strictly it may not be a bug but then the documentation needs to make this clear. The current union and intersection methods inherit from `Set`. However more standard operators are as follows.

Union:

m_U(x) = max(m_A(x), m_B(x))

Intersection:

m_I(x) = min(m_A(x), m_B(x))

For fuzzy sets A, B, with respective membership functions m_A, m_B

**Comment by fkiraly** [comment]
Now I don't think that *we* will need fuzzy sets for anything (because the Kolmogorov axioms seem to be so much more productive for contemporary AI), but of course other users may want them.

Having said that, I believe in the fuzzy communities (no pun intended), a common point of discussion (?) is that on may adopt various different sets of rules/axioms to generalize the standard set operations.

Should the architecture account for this possiblity of making choices when it comes to what "union" etc does for fuzzy sets?

Maybe a possible extension module, if a fuzzy aficionado comes along?

**Comment by fkiraly** [comment]
Or are the max/min rules you suggest by far the dominant choice? In which case making those the default is most sensible.

**Comment by RaphaelS1** [comment]
Yes I had a similar question, it isn't really a bug because there is an element of subjectivity. As these methods use dispatch, there is no harm in adding an argument to `setunion.FuzzySet` called something like `method` with corresponding indices for different types of operations and then whichever is the most common can be used as the default

**Comment by fkiraly** [comment]
Well, @watashiwa-toki might have a better idea and/or opinions.
